/**
 * TypeScript Type Definitions
 *
 * This file contains all the type definitions (interfaces and enums) used throughout the application.
 * Think of these as "contracts" that describe the shape of our data.
 *
 * Key TypeScript Concepts:
 * - interface: Describes the structure of an object (what properties it has and their types)
 * - enum: A set of named constants (like a dropdown list of allowed values)
 * - ?: Makes a property optional (can be undefined)
 * - export: Makes the type available to other files
 */

// ============================================================
// ENUMS - Sets of predefined constant values
// ============================================================

/**
 * EmailType enum - Defines the allowed types of email addresses
 * Using an enum ensures we only use valid values and prevents typos
 */
export enum EmailType {
  WORK = 'WORK',           // Work/business email
  PERSONAL = 'PERSONAL',   // Personal email
  BILLING = 'BILLING',     // Billing-specific email
  OTHER = 'OTHER'          // Any other type
}

/**
 * PhoneType enum - Defines the allowed types of phone numbers
 */
export enum PhoneType {
  MOBILE = 'MOBILE',       // Cell phone
  OFFICE = 'OFFICE',       // Office/work phone
  HOME = 'HOME',           // Home phone
  FAX = 'FAX',             // Fax number
  OTHER = 'OTHER'          // Any other type
}

/**
 * ContactEntityType enum - Specifies whether a contact belongs to a Person or Organization
 * This is used in polymorphic tables (ContactEmail, ContactPhone, ContactAddress)
 */
export enum ContactEntityType {
  PERSON = 'PERSON',             // Contact belongs to a person
  ORGANIZATION = 'ORGANIZATION'  // Contact belongs to an organization
}

/**
 * AddressType enum - Defines the purpose/type of an address
 */
export enum AddressType {
  SHIPPING = 'SHIPPING',   // Shipping address
  BILLING = 'BILLING',     // Billing address
  HOME = 'HOME',           // Home/residential address
  OFFICE = 'OFFICE',       // Office/work address
  OTHER = 'OTHER'          // Any other type
}

/**
 * RelationshipStatus enum - Defines the current status of a personal relationship
 */
export enum RelationshipStatus {
  CURRENT = 'CURRENT',       // Relationship is active
  SEPARATED = 'SEPARATED',   // Separated but not divorced
  DIVORCED = 'DIVORCED',     // Divorced
  DECEASED = 'DECEASED'      // One or both parties deceased
}

// ============================================================
// CORE ENTITY INTERFACES - Database table representations
// ============================================================
// These interfaces mirror the structure of database tables
// The ? symbol means a property is optional (can be null/undefined)

/**
 * Country interface - Represents a country using ISO standard codes
 * Example: { iso_code_2: 'US', country_name: 'United States of America' }
 */
export interface Country {
  iso_code_2: string;        // 2-letter ISO country code (e.g., 'US', 'CA', 'GB')
  country_name: string;      // Full country name
}

/**
 * Region interface - Represents states, provinces, or regions within a country
 * Example: { country_iso_code: 'US', region_code: 'MA', name: 'Massachusetts', type: 'State' }
 */
export interface Region {
  country_iso_code: string;  // Links to Country (e.g., 'US')
  region_code: string;       // State/province code (e.g., 'MA', 'ON')
  name: string;              // Full region name (e.g., 'Massachusetts')
  type?: string;             // Optional: 'State', 'Province', 'Territory', etc.
}

/**
 * Role interface - Represents job titles/roles within organizations
 * Example: { role_id: 1, role_name: 'CEO' }
 */
export interface Role {
  role_id: number;           // Unique identifier (auto-generated by database)
  role_name: string;         // Role name (e.g., 'CEO', 'Manager', 'Director')
}

/**
 * RelationshipType interface - Defines types of personal relationships
 * Example: { relationship_type_id: 1, name: 'Spouse', is_symmetrical: true }
 */
export interface RelationshipType {
  relationship_type_id: number;  // Unique identifier
  name: string;                  // Relationship name (e.g., 'Spouse', 'Parent', 'Child')
  is_symmetrical: boolean;       // true = both directions are the same (Spouse), false = different (Parent/Child)
}

/**
 * Email interface - Represents an email address with metadata
 * Example: { email_id: 1, email_address: 'john@example.com', email_type: 'WORK', is_primary: true }
 */
export interface Email {
  email_id: number;          // Unique identifier
  email_address: string;     // The actual email address
  email_type: EmailType;     // Type of email (WORK, PERSONAL, etc.)
  is_primary?: boolean;      // Optional: true if this is the primary/preferred email
}

/**
 * Phone interface - Represents a phone number with all components
 * Example: { phone_id: 1, country_code: '+1', area_code: '617', local_number: '555-1234', phone_type: 'MOBILE' }
 */
export interface Phone {
  phone_id: number;          // Unique identifier
  country_code?: string;     // Optional: international calling code (e.g., '+1', '+44')
  area_code?: string;        // Optional: area/region code (e.g., '617')
  local_number: string;      // Required: the main phone number
  phone_type: PhoneType;     // Type of phone (MOBILE, OFFICE, etc.)
  extension?: string;        // Optional: extension number for office phones
  is_primary?: boolean;      // Optional: true if this is the primary/preferred phone
}

/**
 * Address interface - Represents a physical address with international support
 * Example: { address_id: 1, address_line_1: '123 Main St', city_locality: 'Boston', region_code: 'MA', postal_code: '02101', country_iso_code: 'US' }
 */
export interface Address {
  address_id: number;        // Unique identifier
  address_line_1: string;    // Required: street address, first line
  address_line_2?: string;   // Optional: apartment, suite, building, etc.
  address_line_3?: string;   // Optional: additional address info
  city_locality: string;     // Required: city or locality name
  region_code?: string;      // Optional: state/province code (e.g., 'MA')
  postal_code?: string;      // Optional: ZIP code or postal code
  country_iso_code: string;  // Required: 2-letter country code (e.g., 'US')
  is_primary?: boolean;      // Optional: true if this is the primary address
  address_type?: AddressType; // Optional: purpose of this address (HOME, OFFICE, etc.)
}

/**
 * Household interface - Represents a group of people living together (e.g., a family)
 * Example: { household_id: 1, household_name: 'The Smith Family', primary_address_id: 5 }
 */
export interface Household {
  household_id: number;          // Unique identifier
  household_name: string;        // Name of the household (e.g., 'The Smith Family')
  primary_address_id?: number;   // Optional: ID of the main household address
  primary_address?: Address;     // Optional: Full address object (populated when fetching from API)
}

/**
 * Person interface - Represents an individual person
 * This is the main entity for storing contact information about people
 *
 * Note: Arrays (emails[], phones[], addresses[]) are populated by the API
 * when fetching a person, providing all contact info in one response
 */
export interface Person {
  person_id: number;             // Unique identifier (auto-generated by database)
  first_name: string;            // Required: person's first name
  middle_name?: string;          // Optional: middle name or initial
  last_name: string;             // Required: person's last/family name
  birth_year?: number;           // Optional: year of birth (e.g., 1990)
  birth_month?: number;          // Optional: month of birth (1-12)
  birth_day?: number;            // Optional: day of birth (1-31)
  preferred_language?: string;   // Optional: ISO language code (e.g., 'en', 'es', 'fr')
  household_id?: number;         // Optional: ID of household this person belongs to
  household?: Household;         // Optional: Full household object (populated when fetching)
  emails?: Email[];              // Optional: Array of all email addresses for this person
  phones?: Phone[];              // Optional: Array of all phone numbers for this person
  addresses?: Address[];         // Optional: Array of all addresses for this person
}

/**
 * Organization interface - Represents a company, nonprofit, or other organization
 * Similar to Person but for organizational entities
 *
 * Organizations can have hierarchical relationships (parent/child companies)
 * and their own contact information
 */
export interface Organization {
  organization_id: number;         // Unique identifier
  name: string;                    // Required: organization name (e.g., 'Acme Corp')
  website?: string;                // Optional: organization's website URL
  parent_organization_id?: number; // Optional: ID of parent organization (for subsidiaries)
  parent_organization?: Organization; // Optional: Full parent organization object
  emails?: Email[];                // Optional: Array of all email addresses (e.g., info@company.com)
  phones?: Phone[];                // Optional: Array of all phone numbers
  addresses?: Address[];           // Optional: Array of all addresses (offices, headquarters, etc.)
}

export interface PersonRelationship {
  person_relationship_id: number;
  person_id_1: number;
  person_id_2: number;
  relationship_type_id: number;
  relationship_type?: RelationshipType;
  status: RelationshipStatus;
  start_date?: Date;
  end_date?: Date;
}

export interface PersonOrganizationRole {
  person_org_role_id: number;
  person_id: number;
  organization_id: number;
  role_id: number;
  role?: Role;
  organization?: Organization;
  start_date: Date;
  end_date?: Date;
}

// Database result types (for raw queries)
export interface ContactEmail {
  contact_email_id: number;
  contact_id: number;
  email_id: number;
  contact_entity_type: ContactEntityType;
  is_primary: boolean;
}

export interface ContactPhone {
  contact_phone_id: number;
  contact_id: number;
  phone_id: number;
  contact_entity_type: ContactEntityType;
  is_primary: boolean;
}

export interface ContactAddress {
  contact_address_id: number;
  contact_id: number;
  address_id: number;
  address_type: AddressType;
  contact_entity_type: ContactEntityType;
}

// Request/Response types for API
export interface CreatePersonRequest {
  first_name: string;
  middle_name?: string;
  last_name: string;
  birth_year?: number;
  birth_month?: number;
  birth_day?: number;
  preferred_language?: string;
  household_id?: number;
  emails?: Array<{
    email_address: string;
    email_type: EmailType;
    is_primary?: boolean;
  }>;
  phones?: Array<{
    country_code?: string;
    area_code?: string;
    local_number: string;
    phone_type: PhoneType;
    extension?: string;
    is_primary?: boolean;
  }>;
  addresses?: Array<{
    address_line_1: string;
    address_line_2?: string;
    address_line_3?: string;
    city_locality: string;
    region_code?: string;
    postal_code?: string;
    country_iso_code: string;
    address_type?: AddressType;
    is_primary?: boolean;
  }>;
}

export interface CreateOrganizationRequest {
  name: string;
  website?: string;
  parent_organization_id?: number;
  emails?: Array<{
    email_address: string;
    email_type: EmailType;
    is_primary?: boolean;
  }>;
  phones?: Array<{
    country_code?: string;
    area_code?: string;
    local_number: string;
    phone_type: PhoneType;
    extension?: string;
    is_primary?: boolean;
  }>;
  addresses?: Array<{
    address_line_1: string;
    address_line_2?: string;
    address_line_3?: string;
    city_locality: string;
    region_code?: string;
    postal_code?: string;
    country_iso_code: string;
    address_type?: AddressType;
    is_primary?: boolean;
  }>;
}
